.PHONY: clean All

All:
	@echo "----------Building project:[ theGreatJoin - Debug ]----------"
	@cd "theGreatJoin" && "$(MAKE)" -f  "theGreatJoin.mk"
clean:
	@echo "----------Cleaning project:[ theGreatJoin - Debug ]----------"
	@cd "theGreatJoin" && "$(MAKE)" -f  "theGreatJoin.mk" clean
