.PHONY: clean All

All:
	@echo "----------Building project:[ specialCase - Debug ]----------"
	@cd "specialCase" && "$(MAKE)" -f  "specialCase.mk"
clean:
	@echo "----------Cleaning project:[ specialCase - Debug ]----------"
	@cd "specialCase" && "$(MAKE)" -f  "specialCase.mk" clean
