.PHONY: clean All

All:
	@echo "----------Building project:[ chegg - Debug ]----------"
	@cd "chegg" && "$(MAKE)" -f  "chegg.mk"
clean:
	@echo "----------Cleaning project:[ chegg - Debug ]----------"
	@cd "chegg" && "$(MAKE)" -f  "chegg.mk" clean
